apiVersion: v2
name: auth-layer-server
description: A Helm chart for Authentication layer server for HederaTheGraph using Keycloak Bitnami chart as a base
type: application
version: 0.1.0-SNAPSHOT
dependencies:
  - alias: keycloak
    name: keycloak
    version: "19.1.0"
    condition: keycloak.enabled
    repository: "https://charts.bitnami.com/bitnami"
