apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-layer-proxy.fullname" . }}-env
data:
    {{- range $key, $value := .Values.configEnv }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
