{{- $clientSecret := .Values.global.auth.clientSecret | default .Values.configSecrets.clientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-layer-proxy.fullname" . }}-secret
type: Opaque
data:
  CLIENT_SECRET: {{ $clientSecret | required "A valid client secret must be provided either via .Values.global.auth.clientSecret or .Values.configSecrets.clientSecret" | b64enc }}
