apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-layer-proxy.fullname" . }}
  labels:
    {{- include "auth-layer-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: {{ .Values.configEnv.PROXY_PORT }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: {{ .Values.configEnv.ENVOY_ADMIN_PORT }}
  selector:
    {{- include "auth-layer-proxy.selectorLabels" . | nindent 4 }}
