apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-layer-proxy.fullname" . }}
  labels:
    {{- include "auth-layer-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .servicePort }}
      targetPort: {{ .containerPort }}
    {{- end }}
  selector:
    {{- include "auth-layer-proxy.selectorLabels" . | nindent 4 }}
