index-node:
  config:
    chains:
      testnet:
        providers:
          - features: ["archive"]
            label: hedera-testnet
            transport: rpc
            url: https://testnet.hashio.io/api

query-node:
  config:
    chains:
      testnet:
        providers:
          - features: ["archive"]
            label: hedera-testnet
            transport: rpc
            url: https://testnet.hashio.io/api
