apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graph-node.fullname" . }}
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
data:
  config.toml: {{ include "graph-node.config" . | b64enc }}
  {{- if not (hasKey .Values.postgres.password "fromSecret") }}
  pgPass: {{ .Values.postgres.password.value | b64enc | quote }}
  {{- end }}
  