apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-node.fullname" . }}
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{-   toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.jsonRpcPort }}
      targetPort: json-rpc
      protocol: TCP
      name: json-rpc
    - port: {{ .Values.service.graphqlPort }}
      targetPort: graphql
      protocol: TCP
      name: graphql
    - port: {{ .Values.service.graphqlWsPort }}
      targetPort: graphql-ws
      protocol: TCP
      name: graphql-ws
    {{- if eq .Values.role "index-node" }}
    - port: {{ .Values.service.indexPort }}
      targetPort: index
      protocol: TCP
      name: index
    {{- end }}
  selector:
    {{- include "graph-node.selectorLabels" . | nindent 4 }}