{{- $name := "hedera-the-graph-passwords" -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "hedera-the-graph.labels" . | nindent 4 }}
  name: {{ $name }}
  namespace: {{ include "hedera-the-graph.namespace" . }}
data:
  PG_PASSWORD: {{ .Values.global.postgresql.password | b64enc | quote }}
  PG_USERNAME: {{ .Values.global.postgresql.username | b64enc | quote }}