{{- $name := "hedera-the-graph-passwords" -}}
{{- $password := coalesce .Values.global.postgresql.password (randAlphaNum 32) -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "hedera-the-graph.labels" . | nindent 4 }}
  name: {{ $name }}
  namespace: {{ include "hedera-the-graph.namespace" . }}
data:
  password: {{ $password | b64enc | quote }}
  repmgr-password: {{ $password | b64enc | quote }}
  admin-password: {{ $password | b64enc | quote }}
  PG_PASSWORD: {{ $password | b64enc | quote }}
  PG_USERNAME: {{ .Values.global.postgresql.username | b64enc | quote }}
