apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hedera-the-graph-node.fullname" . }}-config
  labels:
    {{- include "hedera-the-graph-node.labels" . | nindent 4 }}
data:  
  {{- if not (hasKey .Values.config.ipfs "fromConfigMap") }}  
  IPFS: {{ .Values.config.ipfs.value | quote }}
  {{- end }}
  {{- if not (hasKey .Values.postgres.host "fromConfigMap") }}  
  PG_HOST: {{ .Values.postgres.host.value | quote }}
  {{- end }}
  {{- if not (hasKey .Values.postgres.db "fromConfigMap") }}  
  PG_DB: {{ .Values.postgres.db.value | quote }}
  {{- end }}
