name: Charts

on:
  pull_request:
    branches: [ main, release/**, 7-add-workflow-chart-install]
  push:
    branches: [ main, release/*]
    tags: [ v* ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ct
        uses: helm/chart-testing-action@v2.4.0

      - name: Run lint
        run: ct lint --config .github/ct.yaml --all

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install ct
        uses: helm/chart-testing-action@v2.4.0

      - name: Install chart
        run: ct install --charts charts/hedera-the-graph --config .github/ct.yaml

