name: Starter Example Subgraph

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: build-and-test
    runs-on: smart-contracts-linux-medium

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: subgraphs/starter-example
        run: npm ci

      - name: Build project
        working-directory: subgraphs/starter-example
        run: npm run build

      - name: Test
        working-directory: subgraphs/starter-example
        run: npm run test
